{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1729178496913, "stop": 1729178497474, "uuid": "d243d4bf-f556-41cd-ba3f-2893f875d196", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-I4FH3MC"}, {"name": "thread", "value": "30280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}